### ISSUE TITLE
UI Updates 

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/Harpoon#30]
- [ ] Update footer to include our social media links and state that our data is coming from baking bad. https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=428:16#42695217 

- [ ] "An open source project by Cryptonomic" should link to the Harpoon repo

- [ ] Include units for all displayed values https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=428:16#42695605  

- [ ] wrap text for “endorsements missed" so it doesn't get cut off.  https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=428:16#42702105

- [ ] Add labels above the rewards calculator form fields https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=448:10#42704640

- [ ] If all the fields for the rewards calculator can be filled, automatically populate the rewards table without having the user click the “calculate” button. https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=428:16#42702433

- [ ] Include units for percentage and cycles in the calculation text fields https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=448:10#42702724

- [ ] Truncate the address but have it explained when the user clicks into the text field. https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=428:16#42702899 

- [ ] Add Warning states for calculations  
Warning state 1: https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=736:0#42705186  
Warning state 2: https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=736:934#42705402

- [ ]  Add tooltips for both graphs  https://www.figma.com/file/VERrdWAYLvUvCwQRlXem90?node-id=428:16#42708079

- [ ]  Fix “blocks per hour” y-axis labels so that the numbers make sense
